name: scheduled packaging
# on:
#   schedule:
#   - cron: "0 2 * * 1-5"

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs: 
  build:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: /Users/18haor/.rbenv/shims/fastlane pub
